// Flat config (ESLint 9). `eslint-config-next` v16 exports flat-config arrays
// directly, so no eslintrc compat layer is needed.
import next from "eslint-config-next";
import nextCoreWebVitals from "eslint-config-next/core-web-vitals";

const config = [
  {
    // Build output, deps, and generated data. `.open-next`/`.wrangler` are
    // deploy artifacts; `next-env.d.ts` is regenerated by Next on every build.
    ignores: [
      ".next/**",
      ".open-next/**",
      ".wrangler/**",
      "node_modules/**",
      "next-env.d.ts",
      "public/**",
    ],
  },
  ...next,
  ...nextCoreWebVitals,
];

export default config;
